### ISSUE TITLE
Skeleton for OpenWhisk actions needed by recommendation service

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard-recommendation#3]
Create placeholders for:
* "recommend" action - later implemented with #2 
* "notify" - part of a sequence with recommend to notify store managers
* "get recommendations" to retrieve the objects created by "recommend"
* "acknowledge recommendations" to mark a recommendation as processed (maybe just deleting it)
and their related triggers/sequences when needed

**Comment by l2fprod** [comment]
put together a basis for OpenWhisk actions, including a placeholder for unit tests and a support for webpack to package dependencies not provided by OpenWhisk.

**Comment by rvennam** [comment]
Great! We need to turn this into openwhisk best practices blog/doc
